version: '3.9'

services:
  db:
    container_name: alpha-postgres
    image: postgres
    restart: always
    user: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_NAME: postgres
      POSTGRES_PORT: 5432
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD", "pg_isready", "-q"]
      interval: 5s
      timeout: 5s
      retries: 10

  pgadmin:
    # Probabily you are going to use it, but i like to have and pgadmin when using postgres
    container_name: alpha-pgadmin
    image: dpage/pgadmin4
    restart: always
    ports:
      - "5051:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: root
    depends_on:
      db:
        condition: service_healthy

  django:
    container_name: alpha-django
    build: ./django
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./django/:/usr/src/app/
    ports:
      - 8000:8000
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy
    environment:
      DATABASE_HOST: "db"
      DATABASE_PORT: 5432
      DATABASE_NAME: postgres
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres

  redis:
    container_name: alpha-redis
    image: redis:alpine
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 30

  celery:
    container_name: alpha-celery
    build: ./django
    command: celery -A core worker -l info
    volumes:
      - ./django/:/usr/src/app/
    environment:
      DATABASE_HOST: "db"
      DATABASE_PORT: 5432
      DATABASE_NAME: postgres
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
    depends_on:
      redis:
        condition: service_healthy

  celery-beat:
    container_name: alpha-beat
    build: ./django
    command: celery -A core beat -l info
    volumes:
      - ./django/:/usr/src/app/
    environment:
      DATABASE_HOST: "db"
      DATABASE_PORT: 5432
      DATABASE_NAME: postgres
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
    depends_on:
      redis:
        condition: service_healthy

volumes:
  pg_data:
