# Generated by Django 4.1.7 on 2023-03-14 02:07

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ativo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("code", models.CharField(max_length=5)),
                ("last_evaluation", models.CharField(max_length=10)),
                ("last_day_evaluation", models.CharField(max_length=10)),
                ("variation", models.CharField(max_length=10)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Ativo",
                "verbose_name_plural": "Ativos",
                "ordering": ["updated_at"],
            },
        ),
    ]
