# Generated by Django 4.1.6 on 2023-03-14 12:09

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ativo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "table",
                    models.CharField(
                        choices=[
                            ("Cotacões Intradia", "cotacoes-intradia"),
                            ("BDRs mais negociados", "bdrs-mais-negociados"),
                            ("Fundos Imobiliários", "fundos-imobiliarios"),
                        ],
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("code", models.CharField(max_length=5)),
                (
                    "last_evaluation",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "last_day_evaluation",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("variation", models.CharField(blank=True, max_length=10, null=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Ativo",
                "verbose_name_plural": "Ativos",
                "ordering": ["updated_at"],
            },
        ),
    ]
